/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.api;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pichau
 */
public class AdicionarFilmeFrame extends javax.swing.JFrame {

    public boolean Consultar(String login) throws ClassNotFoundException {
        boolean autenticado = true;
        String sql;
        try {
            
        String myDriver = "com.mysql.jdbc.Driver";
        String myUrl = "jdbc:mysql://127.0.0.1:3306/urmovie";
        Class.forName(myDriver);
        Connection conn = (Connection) DriverManager.getConnection(myUrl, "root", "1234");

            sql = "SELECT nome FROM filme";
            PreparedStatement ps;
            ps = (PreparedStatement) conn.prepareStatement(sql);
            ResultSet rs;
            rs = ps.executeQuery();

            while (rs.next()) {
                if(txtNome.getText().equals(rs.getString("nome"))) autenticado = false;
            } 
                ps.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        return autenticado;
    }
    
    
    public void Adicionar(){
        boolean resposta = false;
        if(!txtNome.getText().isEmpty()&&!txtDiretor.getText().isEmpty()&&!txtAno.getText().isEmpty()&&
            !txtDescricao.getText().isEmpty()){
            try { 
                resposta = Consultar(txtNome.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        if(resposta == true)
    {
        
            try {
                String myDriver = "com.mysql.jdbc.Driver";
                String myUrl = "jdbc:mysql://127.0.0.1:3306/urmovie";
                Class.forName(myDriver);
                Connection conn = (Connection) DriverManager.getConnection(myUrl, "root", "1234");
                String query = "INSERT INTO filme(nome, diretor, ano, descricao, classificao, usuario_id, caminho_foto)"
                    + " VALUES (?, ?, ?, ?, ?, ?, ?)";
        
                PreparedStatement preparedStmt = (PreparedStatement) conn.prepareStatement(query);
                preparedStmt.setString (1, txtNome.getText());
                preparedStmt.setString (2, txtDiretor.getText());
                preparedStmt.setInt(3, Integer.parseInt(txtAno.getText()));
                preparedStmt.setString(4, txtDescricao.getText());
                preparedStmt.setInt(5, Filme.classificao);
                preparedStmt.setInt(6, Usuario.id);
                preparedStmt.setString(7, Filme.caminho_foto);
                preparedStmt.execute();
                conn.close();
        
            }catch (Exception e) {
                System.err.println("Got an exception!");
                System.err.println(e.getMessage());
            }
            JOptionPane.showMessageDialog(null, "O filme foi adicionado a sua conta!");
 
            HomeFrame a = new HomeFrame();
            this.setVisible(false);
            a.setVisible(true);
       
    }else JOptionPane.showMessageDialog(this, "Esse filme já possui cadastro!");
        }else JOptionPane.showMessageDialog(this, "Existe(m) dado(s) vazios! Preencha o(s) campo(s).");
        
    }
    
    
    
    public AdicionarFilmeFrame(){
        initComponents();
        setResizable(false);
        lblCheio1.setVisible(false);
        lblCheio2.setVisible(false);
        lblCheio3.setVisible(false);
        lblCheio4.setVisible(false);
        lblCheio5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCapa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JEditorPane();
        txtNome = new javax.swing.JTextField();
        txtDiretor = new javax.swing.JTextField();
        txtAno = new javax.swing.JFormattedTextField();
        btnUpload = new javax.swing.JButton();
        lblVazio1 = new javax.swing.JLabel();
        lblCheio1 = new javax.swing.JLabel();
        lblVazio2 = new javax.swing.JLabel();
        lblCheio2 = new javax.swing.JLabel();
        lblVazio3 = new javax.swing.JLabel();
        lblCheio3 = new javax.swing.JLabel();
        lblVazio4 = new javax.swing.JLabel();
        lblCheio4 = new javax.swing.JLabel();
        lblVazio5 = new javax.swing.JLabel();
        lblCheio5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        jLabel1.setText("Adicionar Filme");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 34, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Classificação: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Descrição:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Diretor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Ano: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lblCapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/FormaImagem.png"))); // NOI18N
        jPanel1.add(lblCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 110, 90, 90));

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(txtDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 160, 80));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, -1));
        jPanel1.add(txtDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, -1));

        txtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, -1));

        btnUpload.setBackground(new java.awt.Color(204, 255, 255));
        btnUpload.setText("Fazer Upload");
        btnUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 130, -1));

        lblVazio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Vazia.png"))); // NOI18N
        lblVazio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVazio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVazio1MouseClicked(evt);
            }
        });
        jPanel1.add(lblVazio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 30, 30));

        lblCheio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Cheia.png"))); // NOI18N
        lblCheio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblCheio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 30, 30));

        lblVazio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Vazia.png"))); // NOI18N
        lblVazio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVazio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVazio2MouseClicked(evt);
            }
        });
        jPanel1.add(lblVazio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 30, 30));

        lblCheio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Cheia.png"))); // NOI18N
        lblCheio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblCheio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 30, 30));

        lblVazio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Vazia.png"))); // NOI18N
        lblVazio3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVazio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVazio3MouseClicked(evt);
            }
        });
        jPanel1.add(lblVazio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 30, 30));

        lblCheio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Cheia.png"))); // NOI18N
        lblCheio3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblCheio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 30, 30));

        lblVazio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Vazia.png"))); // NOI18N
        lblVazio4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVazio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVazio4MouseClicked(evt);
            }
        });
        jPanel1.add(lblVazio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 30, 30));

        lblCheio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Cheia.png"))); // NOI18N
        lblCheio4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblCheio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 30, 30));

        lblVazio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Vazia.png"))); // NOI18N
        lblVazio5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVazio5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVazio5MouseClicked(evt);
            }
        });
        jPanel1.add(lblVazio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 30, 30));

        lblCheio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/Estrela_Cheia.png"))); // NOI18N
        lblCheio5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblCheio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 30, 30));

        btnVoltar.setBackground(new java.awt.Color(204, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(204, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblVazio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVazio1MouseClicked
        lblCheio1.setVisible(true);
        lblCheio2.setVisible(false);
        lblCheio3.setVisible(false);
        lblCheio4.setVisible(false);
        lblCheio5.setVisible(false);
        Filme.classificao = 1;
    }//GEN-LAST:event_lblVazio1MouseClicked

    private void lblVazio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVazio2MouseClicked
        lblCheio1.setVisible(true);
        lblCheio2.setVisible(true);
        lblCheio3.setVisible(false);
        lblCheio4.setVisible(false);
        lblCheio5.setVisible(false);
        Filme.classificao = 2;
    }//GEN-LAST:event_lblVazio2MouseClicked

    private void lblVazio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVazio3MouseClicked
        lblCheio1.setVisible(true);
        lblCheio2.setVisible(true);
        lblCheio3.setVisible(true);
        lblCheio4.setVisible(false);
        lblCheio5.setVisible(false);
        Filme.classificao = 3;
    }//GEN-LAST:event_lblVazio3MouseClicked

    private void lblVazio4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVazio4MouseClicked
        lblCheio1.setVisible(true);
        lblCheio2.setVisible(true);
        lblCheio3.setVisible(true);
        lblCheio4.setVisible(true);
        lblCheio5.setVisible(false);
        Filme.classificao = 4;
    }//GEN-LAST:event_lblVazio4MouseClicked

    private void lblVazio5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVazio5MouseClicked
        lblCheio1.setVisible(true);
        lblCheio2.setVisible(true);
        lblCheio3.setVisible(true);
        lblCheio4.setVisible(true);
        lblCheio5.setVisible(true);
        Filme.classificao = 5;
    }//GEN-LAST:event_lblVazio5MouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        HomeFrame a = new HomeFrame();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Adicionar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecionar Arquivo");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagem", "jpg", "png");
        fileChooser.setFileFilter(filter);
        int retorno = fileChooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            Filme.caminho_foto = file.getPath();
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = icon.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
            lblCapa.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarFilmeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapa;
    private javax.swing.JLabel lblCheio1;
    private javax.swing.JLabel lblCheio2;
    private javax.swing.JLabel lblCheio3;
    private javax.swing.JLabel lblCheio4;
    private javax.swing.JLabel lblCheio5;
    private javax.swing.JLabel lblVazio1;
    private javax.swing.JLabel lblVazio2;
    private javax.swing.JLabel lblVazio3;
    private javax.swing.JLabel lblVazio4;
    private javax.swing.JLabel lblVazio5;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JEditorPane txtDescricao;
    private javax.swing.JTextField txtDiretor;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}